@startuml
'https://plantuml.com/class-diagram
hide circle
skinparam classAttributeIconSize 0
hide methods

title US21 of Register a New Client

class Client {
    -username : String
    -email : String
    -password : String
    -name : String
    -address : String
    -nif : Integer
    -contactNumber : String
    -internalCode : Integer
}

class Registration {
    -date : Date
    -status : String
}

class System {
    +validateUniqueFields(citizenCardNumber, phoneNumber)
    +generateInternalCode() : Integer
    -lastAssignedCode : Integer
}

System "1" --> "0..*" Client : manages
Client "1" --> "1" Registration : registers

@enduml
