# This is a configuration file in standard configuration file format
# Lines beginning with a hash or semicolon are ignored by the application program.
# Blank lines are also ignored by the application program.

# Persistence mode can be multiple values, in the scope of this application, currently there is only memory.
# Default, and only value for now is "memory"
PERSISTENCE_MODE memory

#Other options