@startuml
hide circle
skinparam classAttributeIconSize 0
hide methods

title Domain Model: Register a New Client

class Administrator {
}

class Client {
    -internalCode : Integer
    -name : String
    -ccNumber : Integer
    -tif : Integer
    -email: String
    -contactNumber: String
}

Administrator "1" -down- "1..*" Client: registers >

@enduml