@startuml
'https://plantuml.com/use-case-diagram

title Use Case Diagram - First Draft

left to right direction

actor :Owner: as Owner
actor :Client: as Client
actor :Agent: as Agent
actor :Manager: as Manager
actor :Administrator: as Administrator

(UC03 - Publish an offer) as (PublishOffer)
(UC04 - Register visit schedule) as (RegisterVisit)
(UC05 - Appreciate an offer) as (AppreciateOffer)
(UC06 - Define commission) as (DefineCommission)
(UC10 - Register Store) as (RegisterBranches)
(UC11 - Register Agent) as (RegisterAgent)
(UC21 - Registration) as (Registration)
(UC07 - Make a lease/sale offer) as (MakeSaleOffer)
(UC09 - Consult Properties) as (ConsultProperties)
(UC10 - Request a visit schedule) as (RequestSchedule)
(UC11 - Make a purchase/lease request) as (MakeRequest)
(UC51 - List all agents) as (ListAgents)

Agent --> (PublishOffer)
Agent --> (RegisterVisit)
Agent --> (AppreciateOffer)
Agent --> (DefineCommission)

Administrator --> (RegisterBranches)
Administrator --> (RegisterAgent)

Client -->(Registration)

Client -->(ConsultProperties)
Client -->(RequestSchedule)
Client -->(MakeRequest)

Owner -->(Registration)
Owner -->(MakeSaleOffer)

Manager -->(ListAgents)


@enduml
