@startuml
hide circle
skinparam classAttributeIconSize 0
hide methods

title Domain Model: Register a New Client

class Administrator {
}

class Client {
    code
    name
    idNumber
    tif
    email
    phoneNumber
}

Administrator "1" -down- "1..*" Client: registers >

@enduml