@startuml
'https://plantuml.com/class-diagram

hide circle
skinparam ClassAttributeIconSize 0
hide methods
skinparam ranksep 50
skinparam nodesep 70

class Agent {
  name
  idNumber
  email
  contactNumber
}

class NetworkManager{}

class Advertisement {
  typeBusiness
  typeProperty
  price
  visibility
}

class Store {
  code
  designation
  address
  openingTime
  closingTime
}

NetworkManager "1" -- "1..*" Agent : views >
Store "1" - "1..*" Agent : has >
Agent "1" - "1..*" Advertisement : receives >


@enduml